---
clone:
  depth: 1

kind: pipeline
type: docker
name: cooking

platform:
  os: linux
  arch: amd64

steps:
  - name: build-kernel
    image: alpine
      - echo "Hello World!"
    environment:
      GIT:
        from_secret: git
      TOKEN:
        from_secret: token
    commands:
      - export git=$GIT
      - export token=$TOKEN
      - export TZ=Europe/Moscow
      - git clone --depth=1 https://github.com/sotodrom/kernel_asus_sdm660-4.19 -b 16 kernel
      - cd kernel
      - curl -LSs https://raw.githubusercontent.com/Sorayukii/KernelSU-Next/stable/kernel/setup.sh | bash -s hookless
      - curl -s https://raw.githubusercontent.com/sotodrom/cooking-kernel/master/build.sh | bash

trigger:
  branch:
    - master
    - main
