--- 
clone: 
  depth: 1
kind: pipeline
name: cooking
steps: 
  - 
    commands:
      - "export git=$GIT"
      - "export token=$TOKEN"
      - "export TZ=Europe/Moscow"
      - "git clone --depth=1 https://github.com/sotodrom/kernel_asus_sdm660-4.19 -b 16 kernel"
      - "cd kernel"
      - "curl -LSs "https://raw.githubusercontent.com/Sorayukii/KernelSU-Next/stable/kernel/setup.sh" | bash -s hookless"
      - "curl -s https://raw.githubusercontent.com/sotodrom/cooking-kernel/master/build.sh | bash"
    environment: 
      GIT:
        from_secret: git
      TOKEN: 
        from_secret: token
    image: atomxorg/arch-linux:kernel
    trigger: 
      branch: 
        - master
