version: 2.1
jobs:
  compile:
   docker:
      - image: wizardprjkt/build:kernel
   steps:
      - run:
          command: |
            git clone --depth=1 --recursive https://github.com/sotodrom/kernel_asus_sdm660 -b clo/eas kernel && cd kernel
            export TZ=Asia/Pontianak
            bash build.sh
          no_output_timeout : 1h
workflows:
  version: 2.1
  cooking:
    jobs:
      - compile
